# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setMouseTracking(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Res = QtWidgets.QPushButton(self.centralwidget)
        self.Res.setGeometry(QtCore.QRect(560, 60, 75, 23))
        self.Res.setObjectName("Res")
        self.ex1_0_0 = QtWidgets.QRadioButton(self.centralwidget)
        self.ex1_0_0.setGeometry(QtCore.QRect(20, 40, 16, 17))
        self.ex1_0_0.setText("")
        self.ex1_0_0.setObjectName("ex1_0_0")
        self.ex1_1_0 = QtWidgets.QRadioButton(self.centralwidget)
        self.ex1_1_0.setGeometry(QtCore.QRect(20, 60, 16, 17))
        self.ex1_1_0.setText("")
        self.ex1_1_0.setObjectName("ex1_1_0")
        self.ex1_2_0 = QtWidgets.QRadioButton(self.centralwidget)
        self.ex1_2_0.setGeometry(QtCore.QRect(20, 80, 16, 17))
        self.ex1_2_0.setText("")
        self.ex1_2_0.setObjectName("ex1_2_0")
        self.ex1_3_0 = QtWidgets.QRadioButton(self.centralwidget)
        self.ex1_3_0.setGeometry(QtCore.QRect(20, 100, 16, 17))
        self.ex1_3_0.setText("")
        self.ex1_3_0.setObjectName("ex1_3_0")
        self.ex1_0_1 = QtWidgets.QRadioButton(self.centralwidget)
        self.ex1_0_1.setGeometry(QtCore.QRect(40, 40, 16, 17))
        self.ex1_0_1.setText("")
        self.ex1_0_1.setObjectName("ex1_0_1")
        self.ex1_1_1 = QtWidgets.QRadioButton(self.centralwidget)
        self.ex1_1_1.setGeometry(QtCore.QRect(40, 60, 16, 17))
        self.ex1_1_1.setText("")
        self.ex1_1_1.setObjectName("ex1_1_1")
        self.ex1_2_1 = QtWidgets.QRadioButton(self.centralwidget)
        self.ex1_2_1.setGeometry(QtCore.QRect(40, 80, 16, 17))
        self.ex1_2_1.setText("")
        self.ex1_2_1.setObjectName("ex1_2_1")
        self.ex1_3_1 = QtWidgets.QRadioButton(self.centralwidget)
        self.ex1_3_1.setGeometry(QtCore.QRect(40, 100, 16, 17))
        self.ex1_3_1.setText("")
        self.ex1_3_1.setObjectName("ex1_3_1")
        self.ex1_3_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.ex1_3_2.setGeometry(QtCore.QRect(60, 100, 16, 17))
        self.ex1_3_2.setText("")
        self.ex1_3_2.setObjectName("ex1_3_2")
        self.ex1_3_3 = QtWidgets.QRadioButton(self.centralwidget)
        self.ex1_3_3.setGeometry(QtCore.QRect(80, 100, 16, 17))
        self.ex1_3_3.setText("")
        self.ex1_3_3.setObjectName("ex1_3_3")
        self.ex1_1_3 = QtWidgets.QRadioButton(self.centralwidget)
        self.ex1_1_3.setGeometry(QtCore.QRect(80, 60, 16, 16))
        self.ex1_1_3.setText("")
        self.ex1_1_3.setObjectName("ex1_1_3")
        self.ex1_2_3 = QtWidgets.QRadioButton(self.centralwidget)
        self.ex1_2_3.setGeometry(QtCore.QRect(80, 80, 16, 17))
        self.ex1_2_3.setText("")
        self.ex1_2_3.setObjectName("ex1_2_3")
        self.ex1_1_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.ex1_1_2.setGeometry(QtCore.QRect(60, 60, 16, 17))
        self.ex1_1_2.setText("")
        self.ex1_1_2.setObjectName("ex1_1_2")
        self.ex1_0_3 = QtWidgets.QRadioButton(self.centralwidget)
        self.ex1_0_3.setGeometry(QtCore.QRect(80, 40, 16, 17))
        self.ex1_0_3.setText("")
        self.ex1_0_3.setObjectName("ex1_0_3")
        self.ex1_2_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.ex1_2_2.setGeometry(QtCore.QRect(60, 80, 16, 17))
        self.ex1_2_2.setText("")
        self.ex1_2_2.setObjectName("ex1_2_2")
        self.ex1_0_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.ex1_0_2.setGeometry(QtCore.QRect(60, 40, 16, 17))
        self.ex1_0_2.setText("")
        self.ex1_0_2.setObjectName("ex1_0_2")
        self.ex2_0_0 = QtWidgets.QRadioButton(self.centralwidget)
        self.ex2_0_0.setGeometry(QtCore.QRect(130, 40, 16, 17))
        self.ex2_0_0.setText("")
        self.ex2_0_0.setObjectName("ex2_0_0")
        self.ex2_1_0 = QtWidgets.QRadioButton(self.centralwidget)
        self.ex2_1_0.setGeometry(QtCore.QRect(130, 60, 16, 17))
        self.ex2_1_0.setText("")
        self.ex2_1_0.setObjectName("ex2_1_0")
        self.ex2_2_0 = QtWidgets.QRadioButton(self.centralwidget)
        self.ex2_2_0.setGeometry(QtCore.QRect(130, 80, 16, 17))
        self.ex2_2_0.setText("")
        self.ex2_2_0.setObjectName("ex2_2_0")
        self.ex2_3_0 = QtWidgets.QRadioButton(self.centralwidget)
        self.ex2_3_0.setGeometry(QtCore.QRect(130, 100, 16, 17))
        self.ex2_3_0.setText("")
        self.ex2_3_0.setObjectName("ex2_3_0")
        self.ex2_3_1 = QtWidgets.QRadioButton(self.centralwidget)
        self.ex2_3_1.setGeometry(QtCore.QRect(150, 100, 16, 17))
        self.ex2_3_1.setText("")
        self.ex2_3_1.setObjectName("ex2_3_1")
        self.ex2_2_1 = QtWidgets.QRadioButton(self.centralwidget)
        self.ex2_2_1.setGeometry(QtCore.QRect(150, 80, 16, 17))
        self.ex2_2_1.setText("")
        self.ex2_2_1.setObjectName("ex2_2_1")
        self.ex2_1_1 = QtWidgets.QRadioButton(self.centralwidget)
        self.ex2_1_1.setGeometry(QtCore.QRect(150, 60, 16, 17))
        self.ex2_1_1.setText("")
        self.ex2_1_1.setObjectName("ex2_1_1")
        self.ex2_0_1 = QtWidgets.QRadioButton(self.centralwidget)
        self.ex2_0_1.setGeometry(QtCore.QRect(150, 40, 16, 17))
        self.ex2_0_1.setText("")
        self.ex2_0_1.setObjectName("ex2_0_1")
        self.ex2_0_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.ex2_0_2.setGeometry(QtCore.QRect(170, 40, 16, 17))
        self.ex2_0_2.setText("")
        self.ex2_0_2.setObjectName("ex2_0_2")
        self.ex2_0_3 = QtWidgets.QRadioButton(self.centralwidget)
        self.ex2_0_3.setGeometry(QtCore.QRect(190, 40, 16, 17))
        self.ex2_0_3.setText("")
        self.ex2_0_3.setObjectName("ex2_0_3")
        self.ex2_1_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.ex2_1_2.setGeometry(QtCore.QRect(170, 60, 16, 17))
        self.ex2_1_2.setText("")
        self.ex2_1_2.setObjectName("ex2_1_2")
        self.ex2_1_3 = QtWidgets.QRadioButton(self.centralwidget)
        self.ex2_1_3.setGeometry(QtCore.QRect(190, 60, 16, 17))
        self.ex2_1_3.setText("")
        self.ex2_1_3.setObjectName("ex2_1_3")
        self.ex2_2_3 = QtWidgets.QRadioButton(self.centralwidget)
        self.ex2_2_3.setGeometry(QtCore.QRect(190, 80, 16, 17))
        self.ex2_2_3.setText("")
        self.ex2_2_3.setObjectName("ex2_2_3")
        self.ex2_2_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.ex2_2_2.setGeometry(QtCore.QRect(170, 80, 16, 17))
        self.ex2_2_2.setText("")
        self.ex2_2_2.setObjectName("ex2_2_2")
        self.ex2_3_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.ex2_3_2.setGeometry(QtCore.QRect(170, 100, 16, 17))
        self.ex2_3_2.setText("")
        self.ex2_3_2.setObjectName("ex2_3_2")
        self.ex2_3_3 = QtWidgets.QRadioButton(self.centralwidget)
        self.ex2_3_3.setGeometry(QtCore.QRect(190, 100, 16, 17))
        self.ex2_3_3.setText("")
        self.ex2_3_3.setObjectName("ex2_3_3")
        self.in1_0 = QtWidgets.QCheckBox(self.centralwidget)
        self.in1_0.setGeometry(QtCore.QRect(460, 60, 16, 20))
        self.in1_0.setText("")
        self.in1_0.setObjectName("in1_0")
        self.in0_0 = QtWidgets.QCheckBox(self.centralwidget)
        self.in0_0.setGeometry(QtCore.QRect(460, 40, 16, 20))
        self.in0_0.setText("")
        self.in0_0.setObjectName("in0_0")
        self.in2_0 = QtWidgets.QCheckBox(self.centralwidget)
        self.in2_0.setGeometry(QtCore.QRect(460, 80, 16, 20))
        self.in2_0.setText("")
        self.in2_0.setObjectName("in2_0")
        self.in3_0 = QtWidgets.QCheckBox(self.centralwidget)
        self.in3_0.setGeometry(QtCore.QRect(460, 100, 16, 20))
        self.in3_0.setText("")
        self.in3_0.setObjectName("in3_0")
        self.in0_1 = QtWidgets.QCheckBox(self.centralwidget)
        self.in0_1.setGeometry(QtCore.QRect(480, 40, 16, 20))
        self.in0_1.setText("")
        self.in0_1.setObjectName("in0_1")
        self.in1_1 = QtWidgets.QCheckBox(self.centralwidget)
        self.in1_1.setGeometry(QtCore.QRect(480, 60, 16, 20))
        self.in1_1.setText("")
        self.in1_1.setObjectName("in1_1")
        self.in2_1 = QtWidgets.QCheckBox(self.centralwidget)
        self.in2_1.setGeometry(QtCore.QRect(480, 80, 16, 20))
        self.in2_1.setText("")
        self.in2_1.setObjectName("in2_1")
        self.in3_1 = QtWidgets.QCheckBox(self.centralwidget)
        self.in3_1.setGeometry(QtCore.QRect(480, 100, 16, 20))
        self.in3_1.setText("")
        self.in3_1.setObjectName("in3_1")
        self.in0_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.in0_2.setGeometry(QtCore.QRect(500, 40, 16, 20))
        self.in0_2.setText("")
        self.in0_2.setObjectName("in0_2")
        self.in0_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.in0_3.setGeometry(QtCore.QRect(520, 40, 16, 20))
        self.in0_3.setText("")
        self.in0_3.setObjectName("in0_3")
        self.in1_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.in1_2.setGeometry(QtCore.QRect(500, 60, 16, 20))
        self.in1_2.setText("")
        self.in1_2.setObjectName("in1_2")
        self.in1_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.in1_3.setGeometry(QtCore.QRect(520, 60, 16, 20))
        self.in1_3.setText("")
        self.in1_3.setObjectName("in1_3")
        self.in2_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.in2_2.setGeometry(QtCore.QRect(500, 80, 16, 20))
        self.in2_2.setText("")
        self.in2_2.setObjectName("in2_2")
        self.in2_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.in2_3.setGeometry(QtCore.QRect(520, 80, 16, 20))
        self.in2_3.setText("")
        self.in2_3.setObjectName("in2_3")
        self.in3_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.in3_2.setGeometry(QtCore.QRect(500, 100, 16, 20))
        self.in3_2.setText("")
        self.in3_2.setObjectName("in3_2")
        self.in3_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.in3_3.setGeometry(QtCore.QRect(520, 100, 16, 20))
        self.in3_3.setText("")
        self.in3_3.setObjectName("in3_3")
        self.ex3_0_0 = QtWidgets.QRadioButton(self.centralwidget)
        self.ex3_0_0.setGeometry(QtCore.QRect(240, 40, 16, 17))
        self.ex3_0_0.setText("")
        self.ex3_0_0.setObjectName("ex3_0_0")
        self.ex3_1_0 = QtWidgets.QRadioButton(self.centralwidget)
        self.ex3_1_0.setGeometry(QtCore.QRect(240, 60, 16, 17))
        self.ex3_1_0.setText("")
        self.ex3_1_0.setObjectName("ex3_1_0")
        self.ex3_2_0 = QtWidgets.QRadioButton(self.centralwidget)
        self.ex3_2_0.setGeometry(QtCore.QRect(240, 80, 16, 17))
        self.ex3_2_0.setText("")
        self.ex3_2_0.setObjectName("ex3_2_0")
        self.ex3_3_0 = QtWidgets.QRadioButton(self.centralwidget)
        self.ex3_3_0.setGeometry(QtCore.QRect(240, 100, 16, 17))
        self.ex3_3_0.setText("")
        self.ex3_3_0.setObjectName("ex3_3_0")
        self.ex3_3_1 = QtWidgets.QRadioButton(self.centralwidget)
        self.ex3_3_1.setGeometry(QtCore.QRect(260, 100, 16, 16))
        self.ex3_3_1.setText("")
        self.ex3_3_1.setObjectName("ex3_3_1")
        self.ex3_3_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.ex3_3_2.setGeometry(QtCore.QRect(280, 100, 16, 17))
        self.ex3_3_2.setText("")
        self.ex3_3_2.setObjectName("ex3_3_2")
        self.ex3_3_3 = QtWidgets.QRadioButton(self.centralwidget)
        self.ex3_3_3.setGeometry(QtCore.QRect(300, 100, 16, 17))
        self.ex3_3_3.setText("")
        self.ex3_3_3.setObjectName("ex3_3_3")
        self.ex3_2_1 = QtWidgets.QRadioButton(self.centralwidget)
        self.ex3_2_1.setGeometry(QtCore.QRect(260, 80, 16, 17))
        self.ex3_2_1.setText("")
        self.ex3_2_1.setObjectName("ex3_2_1")
        self.ex3_2_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.ex3_2_2.setGeometry(QtCore.QRect(280, 80, 16, 17))
        self.ex3_2_2.setText("")
        self.ex3_2_2.setObjectName("ex3_2_2")
        self.ex3_2_3 = QtWidgets.QRadioButton(self.centralwidget)
        self.ex3_2_3.setGeometry(QtCore.QRect(300, 80, 16, 17))
        self.ex3_2_3.setText("")
        self.ex3_2_3.setObjectName("ex3_2_3")
        self.ex3_1_1 = QtWidgets.QRadioButton(self.centralwidget)
        self.ex3_1_1.setGeometry(QtCore.QRect(260, 60, 16, 17))
        self.ex3_1_1.setText("")
        self.ex3_1_1.setObjectName("ex3_1_1")
        self.ex3_0_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.ex3_0_2.setGeometry(QtCore.QRect(280, 40, 16, 17))
        self.ex3_0_2.setText("")
        self.ex3_0_2.setObjectName("ex3_0_2")
        self.ex3_1_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.ex3_1_2.setGeometry(QtCore.QRect(280, 60, 16, 17))
        self.ex3_1_2.setText("")
        self.ex3_1_2.setObjectName("ex3_1_2")
        self.ex3_1_3 = QtWidgets.QRadioButton(self.centralwidget)
        self.ex3_1_3.setGeometry(QtCore.QRect(300, 60, 16, 17))
        self.ex3_1_3.setText("")
        self.ex3_1_3.setObjectName("ex3_1_3")
        self.ex3_0_1 = QtWidgets.QRadioButton(self.centralwidget)
        self.ex3_0_1.setGeometry(QtCore.QRect(260, 40, 16, 17))
        self.ex3_0_1.setText("")
        self.ex3_0_1.setObjectName("ex3_0_1")
        self.ex3_0_3 = QtWidgets.QRadioButton(self.centralwidget)
        self.ex3_0_3.setGeometry(QtCore.QRect(300, 40, 16, 17))
        self.ex3_0_3.setText("")
        self.ex3_0_3.setObjectName("ex3_0_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 20, 47, 13))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(140, 20, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(250, 20, 47, 13))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(460, 20, 91, 16))
        self.label_4.setObjectName("label_4")
        self.ex4_3_1 = QtWidgets.QRadioButton(self.centralwidget)
        self.ex4_3_1.setGeometry(QtCore.QRect(370, 100, 16, 17))
        self.ex4_3_1.setText("")
        self.ex4_3_1.setObjectName("ex4_3_1")
        self.ex4_1_0 = QtWidgets.QRadioButton(self.centralwidget)
        self.ex4_1_0.setGeometry(QtCore.QRect(350, 60, 16, 17))
        self.ex4_1_0.setText("")
        self.ex4_1_0.setObjectName("ex4_1_0")
        self.ex4_0_3 = QtWidgets.QRadioButton(self.centralwidget)
        self.ex4_0_3.setGeometry(QtCore.QRect(410, 40, 16, 17))
        self.ex4_0_3.setText("")
        self.ex4_0_3.setObjectName("ex4_0_3")
        self.ex4_3_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.ex4_3_2.setGeometry(QtCore.QRect(390, 100, 16, 17))
        self.ex4_3_2.setText("")
        self.ex4_3_2.setObjectName("ex4_3_2")
        self.ex4_1_3 = QtWidgets.QRadioButton(self.centralwidget)
        self.ex4_1_3.setGeometry(QtCore.QRect(410, 60, 16, 17))
        self.ex4_1_3.setText("")
        self.ex4_1_3.setObjectName("ex4_1_3")
        self.ex4_2_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.ex4_2_2.setGeometry(QtCore.QRect(390, 80, 16, 17))
        self.ex4_2_2.setText("")
        self.ex4_2_2.setObjectName("ex4_2_2")
        self.ex4_1_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.ex4_1_2.setGeometry(QtCore.QRect(390, 60, 16, 17))
        self.ex4_1_2.setText("")
        self.ex4_1_2.setObjectName("ex4_1_2")
        self.ex4_2_1 = QtWidgets.QRadioButton(self.centralwidget)
        self.ex4_2_1.setGeometry(QtCore.QRect(370, 80, 16, 17))
        self.ex4_2_1.setText("")
        self.ex4_2_1.setObjectName("ex4_2_1")
        self.ex4_1_1 = QtWidgets.QRadioButton(self.centralwidget)
        self.ex4_1_1.setGeometry(QtCore.QRect(370, 60, 16, 17))
        self.ex4_1_1.setText("")
        self.ex4_1_1.setObjectName("ex4_1_1")
        self.ex4_0_1 = QtWidgets.QRadioButton(self.centralwidget)
        self.ex4_0_1.setGeometry(QtCore.QRect(370, 40, 16, 17))
        self.ex4_0_1.setText("")
        self.ex4_0_1.setObjectName("ex4_0_1")
        self.ex4_3_3 = QtWidgets.QRadioButton(self.centralwidget)
        self.ex4_3_3.setGeometry(QtCore.QRect(410, 100, 16, 17))
        self.ex4_3_3.setText("")
        self.ex4_3_3.setObjectName("ex4_3_3")
        self.ex4_3_0 = QtWidgets.QRadioButton(self.centralwidget)
        self.ex4_3_0.setGeometry(QtCore.QRect(350, 100, 16, 17))
        self.ex4_3_0.setText("")
        self.ex4_3_0.setObjectName("ex4_3_0")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(360, 20, 47, 13))
        self.label_5.setObjectName("label_5")
        self.ex4_0_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.ex4_0_2.setGeometry(QtCore.QRect(390, 40, 16, 17))
        self.ex4_0_2.setText("")
        self.ex4_0_2.setObjectName("ex4_0_2")
        self.ex4_0_0 = QtWidgets.QRadioButton(self.centralwidget)
        self.ex4_0_0.setGeometry(QtCore.QRect(350, 40, 16, 17))
        self.ex4_0_0.setText("")
        self.ex4_0_0.setObjectName("ex4_0_0")
        self.ex4_2_0 = QtWidgets.QRadioButton(self.centralwidget)
        self.ex4_2_0.setGeometry(QtCore.QRect(350, 80, 16, 17))
        self.ex4_2_0.setText("")
        self.ex4_2_0.setObjectName("ex4_2_0")
        self.ex4_2_3 = QtWidgets.QRadioButton(self.centralwidget)
        self.ex4_2_3.setGeometry(QtCore.QRect(410, 80, 16, 17))
        self.ex4_2_3.setText("")
        self.ex4_2_3.setObjectName("ex4_2_3")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 130, 151, 16))
        self.label_6.setObjectName("label_6")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(90, 160, 71, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(90, 190, 71, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(90, 220, 71, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(90, 250, 71, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(30, 160, 51, 20))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(30, 250, 51, 20))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(30, 220, 51, 20))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(30, 190, 51, 20))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(210, 130, 91, 16))
        self.label_11.setObjectName("label_11")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(250, 220, 71, 20))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_6.setGeometry(QtCore.QRect(250, 250, 71, 20))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(190, 250, 51, 20))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(190, 190, 51, 20))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(190, 160, 51, 20))
        self.label_14.setObjectName("label_14")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_7.setGeometry(QtCore.QRect(250, 160, 71, 20))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_8.setGeometry(QtCore.QRect(250, 190, 71, 20))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(190, 220, 51, 20))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(350, 250, 51, 20))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(350, 190, 51, 20))
        self.label_17.setObjectName("label_17")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_9.setGeometry(QtCore.QRect(410, 160, 71, 20))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_10.setGeometry(QtCore.QRect(410, 220, 71, 20))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(350, 220, 51, 20))
        self.label_18.setObjectName("label_18")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_11.setGeometry(QtCore.QRect(410, 250, 71, 20))
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(350, 160, 51, 20))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(360, 130, 111, 16))
        self.label_20.setObjectName("label_20")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_12.setGeometry(QtCore.QRect(410, 190, 71, 20))
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_13.setGeometry(QtCore.QRect(570, 220, 71, 20))
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_14.setGeometry(QtCore.QRect(570, 250, 71, 20))
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(510, 250, 51, 20))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(510, 190, 51, 20))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(510, 160, 51, 20))
        self.label_23.setObjectName("label_23")
        self.lineEdit_15 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_15.setGeometry(QtCore.QRect(570, 160, 71, 20))
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(500, 130, 151, 16))
        self.label_24.setObjectName("label_24")
        self.lineEdit_16 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_16.setGeometry(QtCore.QRect(570, 190, 71, 20))
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        self.label_25.setGeometry(QtCore.QRect(510, 220, 51, 20))
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(50, 410, 51, 20))
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.centralwidget)
        self.label_27.setGeometry(QtCore.QRect(50, 380, 51, 20))
        self.label_27.setObjectName("label_27")
        self.lineEdit_17 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_17.setGeometry(QtCore.QRect(110, 410, 71, 20))
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.label_28 = QtWidgets.QLabel(self.centralwidget)
        self.label_28.setGeometry(QtCore.QRect(50, 350, 51, 20))
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.centralwidget)
        self.label_29.setGeometry(QtCore.QRect(50, 320, 51, 20))
        self.label_29.setObjectName("label_29")
        self.lineEdit_18 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_18.setGeometry(QtCore.QRect(110, 320, 71, 20))
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.lineEdit_19 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_19.setGeometry(QtCore.QRect(110, 350, 71, 20))
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.label_30 = QtWidgets.QLabel(self.centralwidget)
        self.label_30.setGeometry(QtCore.QRect(40, 290, 151, 16))
        self.label_30.setObjectName("label_30")
        self.lineEdit_20 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_20.setGeometry(QtCore.QRect(110, 380, 71, 20))
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.lineEdit_21 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_21.setGeometry(QtCore.QRect(320, 410, 71, 20))
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.lineEdit_22 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_22.setGeometry(QtCore.QRect(320, 320, 71, 20))
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.lineEdit_23 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_23.setGeometry(QtCore.QRect(320, 350, 71, 20))
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.label_31 = QtWidgets.QLabel(self.centralwidget)
        self.label_31.setGeometry(QtCore.QRect(260, 380, 51, 20))
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.centralwidget)
        self.label_32.setGeometry(QtCore.QRect(260, 320, 51, 20))
        self.label_32.setObjectName("label_32")
        self.lineEdit_24 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_24.setGeometry(QtCore.QRect(320, 380, 71, 20))
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.label_33 = QtWidgets.QLabel(self.centralwidget)
        self.label_33.setGeometry(QtCore.QRect(260, 410, 51, 20))
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.centralwidget)
        self.label_34.setGeometry(QtCore.QRect(260, 350, 51, 20))
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.centralwidget)
        self.label_35.setGeometry(QtCore.QRect(240, 290, 191, 16))
        self.label_35.setObjectName("label_35")
        self.lineEdit_25 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_25.setGeometry(QtCore.QRect(540, 500, 71, 20))
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.label_36 = QtWidgets.QLabel(self.centralwidget)
        self.label_36.setGeometry(QtCore.QRect(340, 480, 111, 20))
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.centralwidget)
        self.label_37.setGeometry(QtCore.QRect(480, 470, 51, 20))
        self.label_37.setObjectName("label_37")
        self.lineEdit_26 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_26.setGeometry(QtCore.QRect(540, 530, 71, 20))
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.label_38 = QtWidgets.QLabel(self.centralwidget)
        self.label_38.setGeometry(QtCore.QRect(480, 530, 51, 20))
        self.label_38.setObjectName("label_38")
        self.lineEdit_27 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_27.setGeometry(QtCore.QRect(540, 470, 71, 20))
        self.lineEdit_27.setObjectName("lineEdit_27")
        self.label_39 = QtWidgets.QLabel(self.centralwidget)
        self.label_39.setGeometry(QtCore.QRect(480, 500, 51, 20))
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(self.centralwidget)
        self.label_40.setGeometry(QtCore.QRect(480, 440, 51, 20))
        self.label_40.setObjectName("label_40")
        self.lineEdit_28 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_28.setGeometry(QtCore.QRect(540, 440, 71, 20))
        self.lineEdit_28.setObjectName("lineEdit_28")
        self.lineEdit_29 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_29.setGeometry(QtCore.QRect(540, 380, 71, 20))
        self.lineEdit_29.setObjectName("lineEdit_29")
        self.label_41 = QtWidgets.QLabel(self.centralwidget)
        self.label_41.setGeometry(QtCore.QRect(460, 290, 201, 16))
        self.label_41.setObjectName("label_41")
        self.label_42 = QtWidgets.QLabel(self.centralwidget)
        self.label_42.setGeometry(QtCore.QRect(480, 350, 51, 20))
        self.label_42.setObjectName("label_42")
        self.lineEdit_30 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_30.setGeometry(QtCore.QRect(540, 410, 71, 20))
        self.lineEdit_30.setObjectName("lineEdit_30")
        self.label_43 = QtWidgets.QLabel(self.centralwidget)
        self.label_43.setGeometry(QtCore.QRect(480, 410, 51, 20))
        self.label_43.setObjectName("label_43")
        self.lineEdit_31 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_31.setGeometry(QtCore.QRect(540, 350, 71, 20))
        self.lineEdit_31.setObjectName("lineEdit_31")
        self.label_44 = QtWidgets.QLabel(self.centralwidget)
        self.label_44.setGeometry(QtCore.QRect(480, 380, 51, 20))
        self.label_44.setObjectName("label_44")
        self.label_45 = QtWidgets.QLabel(self.centralwidget)
        self.label_45.setGeometry(QtCore.QRect(480, 320, 51, 20))
        self.label_45.setObjectName("label_45")
        self.lineEdit_32 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_32.setGeometry(QtCore.QRect(540, 320, 71, 20))
        self.lineEdit_32.setObjectName("lineEdit_32")
        self.lineEdit_33 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_33.setGeometry(QtCore.QRect(250, 500, 71, 20))
        self.lineEdit_33.setObjectName("lineEdit_33")
        self.label_47 = QtWidgets.QLabel(self.centralwidget)
        self.label_47.setGeometry(QtCore.QRect(190, 470, 51, 20))
        self.label_47.setObjectName("label_47")
        self.lineEdit_34 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_34.setGeometry(QtCore.QRect(250, 530, 71, 20))
        self.lineEdit_34.setObjectName("lineEdit_34")
        self.label_48 = QtWidgets.QLabel(self.centralwidget)
        self.label_48.setGeometry(QtCore.QRect(190, 530, 51, 20))
        self.label_48.setObjectName("label_48")
        self.lineEdit_35 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_35.setGeometry(QtCore.QRect(250, 470, 71, 20))
        self.lineEdit_35.setObjectName("lineEdit_35")
        self.label_49 = QtWidgets.QLabel(self.centralwidget)
        self.label_49.setGeometry(QtCore.QRect(190, 500, 51, 20))
        self.label_49.setObjectName("label_49")
        self.label_50 = QtWidgets.QLabel(self.centralwidget)
        self.label_50.setGeometry(QtCore.QRect(190, 440, 51, 20))
        self.label_50.setObjectName("label_50")
        self.lineEdit_36 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_36.setGeometry(QtCore.QRect(250, 440, 71, 20))
        self.lineEdit_36.setObjectName("lineEdit_36")
        self.label_46 = QtWidgets.QLabel(self.centralwidget)
        self.label_46.setGeometry(QtCore.QRect(30, 480, 191, 16))
        self.label_46.setObjectName("label_46")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 700, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Лаба1 -Распознование"))
        self.Res.setText(_translate("MainWindow", "Результат"))
        self.label.setText(_translate("MainWindow", "Эталон 1"))
        self.label_2.setText(_translate("MainWindow", "Эталон 2"))
        self.label_3.setText(_translate("MainWindow", "Эталон 3"))
        self.label_4.setText(_translate("MainWindow", "Распознаваемый"))
        self.label_5.setText(_translate("MainWindow", "Эталон 4"))
        self.label_6.setText(_translate("MainWindow", "Растояние по Минковскому:"))
        self.label_7.setText(_translate("MainWindow", "Эталон 1:"))
        self.label_8.setText(_translate("MainWindow", "Эталон 4:"))
        self.label_9.setText(_translate("MainWindow", "Эталон 3:"))
        self.label_10.setText(_translate("MainWindow", "Эталон 2:"))
        self.label_11.setText(_translate("MainWindow", "Сумма модулей:"))
        self.label_12.setText(_translate("MainWindow", "Эталон 4:"))
        self.label_13.setText(_translate("MainWindow", "Эталон 2:"))
        self.label_14.setText(_translate("MainWindow", "Эталон 1:"))
        self.label_15.setText(_translate("MainWindow", "Эталон 3:"))
        self.label_16.setText(_translate("MainWindow", "Эталон 4:"))
        self.label_17.setText(_translate("MainWindow", "Эталон 2:"))
        self.label_18.setText(_translate("MainWindow", "Эталон 3:"))
        self.label_19.setText(_translate("MainWindow", "Эталон 1:"))
        self.label_20.setText(_translate("MainWindow", "Сумма модулей с n:"))
        self.label_21.setText(_translate("MainWindow", "Эталон 4:"))
        self.label_22.setText(_translate("MainWindow", "Эталон 2:"))
        self.label_23.setText(_translate("MainWindow", "Эталон 1:"))
        self.label_24.setText(_translate("MainWindow", "Растояние по Кендалу:"))
        self.label_25.setText(_translate("MainWindow", "Эталон 3:"))
        self.label_26.setText(_translate("MainWindow", "Эталон 4:"))
        self.label_27.setText(_translate("MainWindow", "Эталон 3:"))
        self.label_28.setText(_translate("MainWindow", "Эталон 2:"))
        self.label_29.setText(_translate("MainWindow", "Эталон 1:"))
        self.label_30.setText(_translate("MainWindow", "Растояние по Чебышеву:"))
        self.label_31.setText(_translate("MainWindow", "Эталон 3:"))
        self.label_32.setText(_translate("MainWindow", "Эталон 1:"))
        self.label_33.setText(_translate("MainWindow", "Эталон 4:"))
        self.label_34.setText(_translate("MainWindow", "Эталон 2:"))
        self.label_35.setText(_translate("MainWindow", "Ф-ция сходства по Сокаля и Снифа:"))
        self.label_36.setText(_translate("MainWindow", "Ф-ция схоства Юла:"))
        self.label_37.setText(_translate("MainWindow", "Эталон 2:"))
        self.label_38.setText(_translate("MainWindow", "Эталон 4:"))
        self.label_39.setText(_translate("MainWindow", "Эталон 3:"))
        self.label_40.setText(_translate("MainWindow", "Эталон 1:"))
        self.label_41.setText(_translate("MainWindow", "Ф-ция сходства по Сокаля и Мишнера:"))
        self.label_42.setText(_translate("MainWindow", "Эталон 2:"))
        self.label_43.setText(_translate("MainWindow", "Эталон 4:"))
        self.label_44.setText(_translate("MainWindow", "Эталон 3:"))
        self.label_45.setText(_translate("MainWindow", "Эталон 1:"))
        self.label_47.setText(_translate("MainWindow", "Эталон 2:"))
        self.label_48.setText(_translate("MainWindow", "Эталон 4:"))
        self.label_49.setText(_translate("MainWindow", "Эталон 3:"))
        self.label_50.setText(_translate("MainWindow", "Эталон 1:"))
        self.label_46.setText(_translate("MainWindow", "Ф-ция сходства Кульжинского:"))

